# Generated by Django 6.1 on 2026-08-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supabase_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAnalysisLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('analysis_date', models.DateField(unique=True)),
                ('user_instruction', models.TextField(blank=True, null=True)),
                ('analysis_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_analysis_log',
                'managed': False,
            },
        ),
    ]
