# Generated by Django 6.1 on 2026-09-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nevera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neveraitem',
            name='es_basico',
            field=models.BooleanField(default=False, help_text='Si está marcado: no entra en el ranking de caducidad y /hecho no le descuenta cantidad. Solo sale del inventario al borrarlo a mano.', verbose_name='básico de despensa'),
        ),
    ]
