# Generated by Django 6.1 on 2026-08-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateSamples',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent_key', models.BigIntegerField()),
                ('bpm', models.SmallIntegerField()),
                ('recorded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'heart_rate_samples',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OxygenSaturationSamples',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.TextField(unique=True)),
                ('recorded_at', models.DateTimeField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'oxygen_saturation_samples',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestingHeartRateSamples',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.TextField(unique=True)),
                ('resting_bpm', models.SmallIntegerField()),
                ('recorded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'resting_heart_rate_samples',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SleepStages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent_key', models.BigIntegerField()),
                ('stage_type', models.SmallIntegerField()),
                ('stage_start', models.DateTimeField()),
                ('stage_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'sleep_stages',
                'managed': False,
            },
        ),
    ]
