# Generated by Django 6.1 on 2026-08-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeveraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('fecha_añadido', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(choices=[('compra', 'Compra'), ('manual', 'Manual')], default='manual', max_length=10)),
            ],
            options={
                'db_table': 'nevera_items',
                'constraints': [models.UniqueConstraint(fields=('nombre', 'unidad'), name='unique_nombre_unidad')],
            },
        ),
    ]
